name: CI/CD
on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install depencies
        run: |
          npm install
        working-directory: ./app
      
      - name: Run test
        run: |
          npm test
        working-directory: ./app
  
  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: AWS authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-duration-seconds: 1200
          role-session-name: ${{ github.sha }}
          aws-region: us-east-1
      
      - name: Login AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Docker build and push
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}:${{ github.sha }} .
          docker push ${{ steps.login-ecr.outputs.registry }}:${{ github.sha }}
        working-directory: ./app
      
      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name daveops-eks
          kubectl set image deployment/app app=${{ steps.login-ecr.outputs.registry }}:${{ github.sha }}