name: PR Check
on:
  - pull_request

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install depencies
        run: |
          npm install
        working-directory: ./app
      
      - name: Run test
        run: |
          npm test
        working-directory: ./app
        